### ISSUE TITLE
Support rendering of strikethrough text (<del>...</del>)

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/vector-android#544] opened 2016-09-21 20:29 UTC

**Comment by ylecollen** [comment] 2016-10-04 14:26
Duplicate of https://github.com/vector-im/vector-android/issues/545

**Closed by ylecollen** 2016-10-04 14:26 UTC
Labels: enhancement, P3

**Comment by Matrixcoffee** [comment] 2016-10-04 21:12
I don't understand why this bug is a duplicate of #545. In #545 you say that strikethrough is parsed correctly, but not rendered, and closed that bug. This bug is about the not rendering.

**Comment by Matrixcoffee** [comment] 2018-03-23 11:00
This is not a duplicate. #545 is about converting `~~text~~` in the input box into the proper html. This bug is about the generated HTML not displaying properly on older Androids.

**Comment by Matrixcoffee** [comment] 2018-03-23 11:01
This is not a duplicate. #545 is about converting `~~text~~` in the input box into the proper HTML. This bug is about the generated HTML not displaying properly on older Androids.

**Comment by Matrixcoffee** [comment] 2018-03-23 11:09
Also note that this issue is independent from anything related to Markdown, as the HTML could have been generated in some other way. There are integrations, and there are other clients than Riot.
