### ISSUE TITLE
Searching for users doesn't work without permission to contacts

### ISSUE THREAD

**Issue by oddvar** [vector-im/vector-android#273] opened 2016-07-04 15:07 UTC
A user tried to search and add @ Kat:matrix.org but couldn't find her due to not having given the app access to his contacts.

**Comment by ylecollen** [comment] 2016-07-04 16:11
The clients only perform a local search i.e if the user id must be found the in joined room members list or from the contacts.

To add an undefined member id, the user has to create a room and add the new member by his matrix id.

**Comment by ylecollen** [comment] 2016-07-05 07:52
I put to p2 because Oddvar failed to reproduce his issue.
He tried to invite an user by matrix ID and it seems that it did not work properly.

**Comment by ylecollen** [comment] 2016-07-06 08:30
Close the issue because it was reproduced.

**Closed by ylecollen** 2016-07-06 08:30 UTC
Labels: bug, P2
