### ISSUE TITLE
register users without email verification 

### ISSUE THREAD

**Issue by farenhite** [vector-im/vector-android#503] opened 2016-09-14 11:38 UTC
vector is very good.please add ability to users can register without email verification on custom servers

**Comment by ara4n** [comment] 2016-09-14 11:41
Email registration should always be optional?  Just leave the email 
address blank?

**Comment by farenhite** [comment] 2016-09-14 11:54
i mean from android client not from web. from web yes its true i can leave the email blank and its ok but when i try to register from android client and leave it blank i get error on my custom server but when home server is matrix.org when i leave email blank it go to capture section and then ok whats problem? problem is my home server config?so what can i do

**Comment by ylecollen** [comment] 2016-09-14 13:02
As you said, it works properly with matrix.org HS.

Which error message  do you have ?
I assume there is something wrong in the android client registration flow with your HS.

Could you provide us your HS URL ? we could test (and fix) where the issue is.

**Comment by farenhite** [comment] 2016-09-15 07:03
my HS url = https://104.237.225.220:8448

and my android studio log and error is:

09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: <--- HTTP 400 https://104.237.225.220:8448/_matrix/client/r0/register (946ms)
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: : HTTP/1.1 400 Bad Request
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Access-Control-Allow-Origin: *
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Content-Type: application/json
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Date: Thu, 15 Sep 2016 06:57:17 GMT
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: OkHttp-Received-Millis: 1473922637163
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: OkHttp-Response-Source: NETWORK 400
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: OkHttp-Selected-Protocol: http/1.1
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: OkHttp-Sent-Millis: 1473922636687
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Server: Synapse/0.17.2
09-15 02:57:17.164 2287-2424/im.vector.alpha D/Retrofit: Transfer-Encoding: chunked
09-15 02:57:17.166 515-795/? E/genymotion_audio: pcm_open(out) failed: cannot open device '/dev/snd/pcmC0D0p': No such file or directory
09-15 02:57:17.168 2287-2424/im.vector.alpha D/Retrofit: {"errcode":"M_MISSING_PARAM","error":""}
09-15 02:57:17.168 2287-2424/im.vector.alpha D/Retrofit: <--- END HTTP (40-byte body)
09-15 02:57:17.186 515-795/? E/genymotion_audio: pcm_open(out) failed: cannot open device '/dev/snd/pcmC0D0p': No such file or directory
09-15 02:57:17.190 2287-2287/im.vector.alpha D/RestAdapterCallback: Failed : [register]
09-15 02:57:17.190 2287-2287/im.vector.alpha D/LoginActivity: ## register(): onMatrixError - Msg=
09-15 02:57:17.190 2287-2287/im.vector.alpha D/LoginActivity: ## register(): The registration continues
09-15 02:57:17.190 2287-2287/im.vector.alpha D/LoginActivity: ## register(): Received not expected status 401 =400
09-15 02:57:17.193 2287-2287/im.vector.alpha E/LoginActivity: ## onFailureDuringAuthRequest(): Msg= ""

**Comment by ylecollen** [comment] 2016-09-15 07:34
your server sends there is a missing parameter.

{"auth":{"type":"m.login.password","session":"WmqeFgRBXgVUaQROzTgWKttJ"},"bind_email":true,"password":"qwerty","username":"ylc001"}

I have the same issue with the same webclient (** Registration failed on server**)

**Comment by farenhite** [comment] 2016-09-15 07:46
so what can i do?

**Comment by ylecollen** [comment] 2016-09-15 07:50
you have to discuss about it with the server team.

Are you using the latest server code ?

**Comment by farenhite** [comment] 2016-09-15 07:50
but with my vector webclient i have no problem baryaban.com/vector check it please

**Comment by ylecollen** [comment] 2016-09-15 07:54
I don't have time to check each webclient version.

I tested with https://vector.im/develop/#/register and it did not work.

**Comment by ylecollen** [comment] 2016-09-15 07:56
according to your webclient 

HS : https://104.237.225.220:8448
IS : matrix.org.

You did not tell us that.

**Comment by farenhite** [comment] 2016-09-15 07:57
ok Synapse v0.17.2 is the last version and i used this version but for test i install synapse using docker this time but same issue https://registry.hub.docker.com/u/silviof/docker-matrix/

**Comment by farenhite** [comment] 2016-09-15 07:59
so i have to change Identity server: https://matrix.org to vector.im ?

**Comment by ylecollen** [comment] 2016-09-15 08:03
i reproduce your issue on the android client.

**Comment by farenhite** [comment] 2016-09-15 08:07
thanks  i am waiting for it and when its done and ready to download?

**Comment by ylecollen** [comment] 2016-09-15 08:12
it will be fixed later (at least not today).
This issue will be closed when it will be fixed.

**Comment by farenhite** [comment] 2016-09-17 06:22
hi i know you are busy and dont have time but please fix this issue today if you can thank you so much

**Comment by farenhite** [comment] 2016-09-21 09:19
please fix this ylecollen

**Comment by farenhite** [comment] 2016-09-23 13:45
hi can you fix this issue first please because this is very important for me i know maybe other issues are more important but please fix it sooner

**Comment by ylecollen** [comment] 2016-09-23 13:51
farenhite  

Your home server configuration for create account is 

-> on Vector.im Home server, the account creation can be done with
--> captcha (i.e without email)
--> email identity + captcha 

On your home server
--> m.login.dummy : we don't support it
--> email identity

**Comment by farenhite** [comment] 2016-09-24 13:48
thanks  ylecollen but from web it can be done without email and captcha .can u help me do it with webview in android? when click on register button in android go to web client for example vector,im or to baryaban.com/chat and then enter user name and password and then capture details and get to login activity? or something like this u know better than me

**Closed** 2016-11-18 13:55 UTC
Labels: bug, P2
