### ISSUE TITLE
Layout broken with RTL languages

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-android#756] opened 2016-11-28 17:13 UTC
See https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$148000080747320GOTMn:matrix.org. Cause turns out to be using the phone in an RTL langauge.

Moved from https://github.com/vector-im/vector-web/issues/2639 (accidentally filed on vector-web).

**Comment by ylecollen** [comment] 2016-11-29 12:06
duplicate of https://github.com/vector-im/vector-android/issues/749

**Closed by ylecollen** 2016-11-29 12:06 UTC
