### ISSUE TITLE
Consider changing to the new android permission system

### ISSUE THREAD

**Issue by oddvar** [vector-im/vector-android#126] opened 2016-05-13 15:27 UTC
New permission system is like iOS: it will ask for permission on-demand. http://developer.android.com/training/permissions/requesting.html - much nicer, IMO

**Comment by ylecollen** [comment] 2016-05-13 15:42
duplicate of 
https://github.com/vector-im/vector-android/issues/74

**Closed by ylecollen** 2016-05-13 15:42 UTC
Labels: enhancement
