### ISSUE TITLE
Inbound calls can still get stuck in a state where you can't decline them

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#400] opened 2016-08-22 21:09 UTC
Might be specific to m.call.invite's appearing in group rooms, but i thought i'd seen vdh suffer this too.  See https://vector.im/develop/#/room/!DgvjtOljKujDBrxyHk:matrix.org/$14718987041116kwLne:ralith.com for specifics

**Comment by richvdh** [comment] 2016-08-23 07:48
I think what I've seen is that, if Vector is backgrounded, the device is notified for the new call, but *isn't* notified if you pick up the call on another device. So the first device keeps ringing and is generally confused

**Comment by ylecollen** [comment] 2016-09-01 13:16
duplicate of https://github.com/vector-im/vector-android/issues/437

**Closed by ylecollen** 2016-09-01 13:16 UTC
Labels: bug, P1
